In [1]:
# Multiple Linear Regression

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [7]:
# Importing the dataset
dataset = pd.read_csv(r'C:\Users\abc\Desktop\Life Expectancy Data.csv')

# Preprocessing data:

# 1. handling missing data

In [8]:
# Taking care of missing data
from sklearn.impute import SimpleImputer #sklearn is library

In [9]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') #nan is not a number
imputer = imputer.fit(dataset.iloc[:, 3:]) # fit calculates mean 
dataset.iloc[:, 3:] = imputer.transform(dataset.iloc[:, 3:]) #transform means to apply

# 2. converting categorical data to numerical data

In [11]:
# Encoding categorical data ie converting categorical to numerical
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
dataset.iloc[:, :1] = labelencoder_X.fit_transform(dataset.iloc[:, :1])

C:\Users\abc\Anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [12]:
# Encoding categorical data ie converting categorical to numerical
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
dataset.iloc[:, 1] = labelencoder_X.fit_transform(dataset.iloc[:, 1])

In [13]:
# Encoding categorical data ie converting categorical to numerical
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
dataset.iloc[:, 2] = labelencoder_X.fit_transform(dataset.iloc[:, 2])

In [14]:
dataset.iloc[:, :1]

      Country
0           0
1           0
2           0
3           0
4           0
...       ...
2933      192
2934      192
2935      192
2936      192
2937      192

[2938 rows x 1 columns]

In [15]:
dataset.iloc[:, 1]

0       15
1       14
2       13
3       12
4       11
        ..
2933     4
2934     3
2935     2
2936     1
2937     0
Name: Year, Length: 2938, dtype: int64

In [16]:
dataset.iloc[:, 2]

0       1
1       1
2       1
3       1
4       1
       ..
2933    1
2934    1
2935    1
2936    1
2937    1
Name: Status, Length: 2938, dtype: int32

# Dataset after data preprocessing:

In [17]:
dataset

,Country,Year,Status,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,...,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Life expectancy
0,0,15,1,263.0,62.0,0.01,71.279624,65.0,1154.0,19.1,...,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1,65.0
1,0,14,1,271.0,64.0,0.01,73.523582,62.0,492.0,18.6,...,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0,59.9
2,0,13,1,268.0,66.0,0.01,73.219243,64.0,430.0,18.1,...,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9,59.9
3,0,12,1,272.0,69.0,0.01,78.184215,67.0,2787.0,17.6,...,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8,59.5
4,0,11,1,275.0,71.0,0.01,7.097109,68.0,3013.0,17.2,...,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5,59.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,192,4,1,723.0,27.0,4.36,0.000000,68.0,31.0,27.1,...,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2,44.3
2934,192,3,1,715.0,26.0,4.06,0.000000,7.0,998.0,26.7,...,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5,44.5
2935,192,2,1,73.0,25.0,4.43,0.000000,73.0,304.0,26.3,...,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0,44.8
2936,192,1,1,686.0,25.0,1.72,0.000000,76.0,529.0,25.9,...,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8,45.3
2937,192,0,1,665.0,24.0,1.68,0.000000,79.0,1483.0,25.5,...,7.10,78.0,43.5,547.358879,12222251.0,11.0,11.2,0.434,9.8,46.0

# seperating dependent and independent variables

In [18]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 21].values

In [19]:
X

array([[  0.   ,  15.   ,   1.   , ...,  17.3  ,   0.479,  10.1  ],
       [  0.   ,  14.   ,   1.   , ...,  17.5  ,   0.476,  10.   ],
       [  0.   ,  13.   ,   1.   , ...,  17.7  ,   0.47 ,   9.9  ],
       ...,
       [192.   ,   2.   ,   1.   , ...,   1.3  ,   0.427,  10.   ],
       [192.   ,   1.   ,   1.   , ...,   1.7  ,   0.427,   9.8  ],
       [192.   ,   0.   ,   1.   , ...,  11.2  ,   0.434,   9.8  ]])

In [20]:
y

array([65. , 59.9, 59.9, ..., 44.8, 45.3, 46. ])

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

# performing multilinear regression

In [23]:
# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [24]:
# Predicting the Test set results
y_pred = regressor.predict(X_test)

In [26]:
y_pred

array([80.60923888, 74.15747389, 75.65456555, 79.62317163, 83.48275745,
       70.4387663 , 63.71514444, 74.72537499, 73.29745685, 71.28052457,
       55.09237812, 61.42399362, 79.71856687, 73.82178673, 61.07268323,
       72.60203538, 69.34613251, 70.34445519, 72.86866293, 75.14894241,
       69.53162183, 72.92089831, 61.82369807, 64.53501069, 68.33753364,
       71.92242949, 68.69680349, 69.70950583, 81.00033527, 81.5860778 ,
       61.45040483, 61.34935613, 57.04504858, 65.39004462, 75.4729981 ,
       84.55415092, 73.65900472, 77.12236714, 72.39063733, 81.52537754,
       69.24253059, 73.92303042, 65.03075556, 85.00786982, 52.20391776,
       73.26551636, 76.57704922, 63.5039404 , 69.24378516, 58.74702327,
       69.13962427, 70.98423276, 76.97936589, 66.84867943, 54.42224161,
       72.51970623, 82.34532234, 72.67182771, 82.59754419, 67.50662992,
       76.30879991, 70.65076766, 70.53397818, 58.74931705, 79.09849881,
       68.40179375, 73.85395249, 67.73425044, 64.88442345, 68.67210287,
       55.42747668, 55.73298029, 75.39368681, 80.08826341, 84.14416261,
       73.9877999 , 67.01401153, 73.73577931, 56.89819699, 82.1990337 ,
       59.70587917, 69.52102773, 77.08804794, 69.20483293, 72.82501789,
       67.86207528, 78.04432684, 80.21713323, 72.63378218, 72.93446133,
       78.73391943, 63.91730792, 78.88976322, 68.6990106 , 76.24292709,
       40.55142533, 74.16553717, 73.78877801, 55.7203308 , 79.7651008 ,
       76.87326698, 73.01472953, 59.85919048, 80.68442871, 72.92582471,
       84.50259593, 74.27273222, 70.28374213, 71.70719239, 58.07930153,
       61.42322927, 71.56839744, 75.49600512, 63.65280326, 78.84456053,
       72.84346634, 59.52433904, 71.31844836, 59.17794699, 70.77508153,
       61.11669918, 62.4520305 , 70.55062244, 72.61665198, 67.95510541,
       65.03703116, 58.10004143, 81.44059905, 62.85090045, 55.89540335,
       64.53589575, 73.52965926, 76.2991342 , 81.44987801, 44.76297209,
       80.70291758, 74.58382228, 69.01813935, 72.93940049, 75.34828398,
       61.31508905, 63.18480156, 69.73826077, 80.1353985 , 58.36673213,
       77.71407053, 76.49294943, 74.50225356, 73.90665345, 60.8936098 ,
       70.24758282, 72.58963391, 45.9302307 , 66.87582038, 71.47551408,
       61.00405736, 59.91536248, 62.40427711, 71.23608509, 68.09492168,
       82.49465043, 45.37000731, 69.14789246, 64.17877137, 69.49689824,
       46.80774289, 59.31751017, 67.98652454, 73.67737144, 74.0247964 ,
       74.63776209, 50.05254711, 80.87896599, 64.62212124, 74.92713009,
       78.13696361, 62.91850101, 35.65933661, 74.45021941, 69.15653386,
       68.77085135, 75.11500294, 68.36193622, 73.77524531, 69.58333807,
       70.79183238, 76.27747309, 35.99038787, 62.31858485, 68.26298734,
       68.38788147, 49.28763921, 72.20482206, 77.02570119, 74.78374281,
       76.04244932, 71.62577033, 58.7580713 , 72.2598745 , 75.49052362,
       62.77436873, 78.67423158, 56.6327092 , 74.75684234, 72.12634649,
       72.69540954, 79.38771035, 52.35247371, 72.98802727, 78.9076815 ,
       72.7595739 , 81.45576553, 55.98247583, 72.27271089, 48.74418853,
       61.15389007, 79.71586988, 55.97422059, 68.11264089, 53.00767768,
       77.01456014, 79.28165481, 78.08696165, 68.87553607, 70.75684684,
       63.43812394, 57.46464832, 75.49721885, 65.42323185, 63.88747709,
       62.08377091, 72.59637141, 73.33055451, 81.77225459, 77.86860424,
       74.56865966, 68.49902497, 69.5194509 , 75.92027714, 60.15173588,
       77.31824949, 75.49432029, 58.33431324, 80.36938102, 75.4264955 ,
       69.22520209, 69.9202671 , 79.02045962, 60.15674771, 59.47573093,
       52.81873948, 76.74189837, 58.46769448, 80.7658212 , 60.41292305,
       73.94782562, 52.20843457, 81.29645567, 84.63636838, 69.88716583,
       55.85421501, 85.05755471, 82.19997888, 75.82790283, 81.94187695,
       79.55946853, 80.36868744, 81.85411033, 76.00183513, 78.79143361,
       79.72780303, 67.44346113, 57.63002948, 64.41547962, 68.24803333,
       59.57139274, 78.06877651, 75.29662833, 59.47278464, 74.67444448,
       77.11176796, 65.30724258, 76.11478999, 71.73086794, 44.15877315,
       57.7277382 , 63.38578193, 75.10207229, 64.57656943, 57.1990512 ,
       53.22801115, 73.49216331, 77.37543547, 69.4071257 , 53.1552707 ,
       63.1017528 , 71.49618445, 75.07118962, 73.80454072, 64.42431713,
       69.66854245, 81.26577436, 67.94325135, 71.92521179, 62.64029878,
       73.46780802, 78.22085209, 73.43451586, 71.3056297 , 64.73144042,
       72.84762037, 70.33119251, 77.08921178, 74.44042986, 70.89313155,
       73.66440055, 74.4649981 , 70.68932866, 73.01252468, 53.88029674,
       64.67745395, 73.06012549, 78.14930856, 75.09818349, 71.34680397,
       46.00638921, 70.4343997 , 64.59709745, 65.50774954, 72.65229368,
       47.91650633, 71.65438412, 72.11713731, 52.12021035, 64.09696731,
       67.03778573, 52.44562162, 56.84252605, 72.26364339, 68.21144977,
       77.29274045, 54.10986817, 62.48075848, 71.81466505, 74.99024764,
       65.85371762, 71.73004511, 60.56337286, 72.56410683, 63.32992374,
       75.84548154, 75.7347899 , 75.81191111, 75.3679609 , 78.31366748,
       72.35627802, 74.11610969, 76.3798133 , 62.54030021, 71.44869918,
       61.34672403, 78.21780979, 68.86545423, 78.60951285, 52.48686353,
       75.14244394, 64.95173517, 50.22316215, 83.81240684, 66.89457552,
       53.32896875, 51.07218501, 53.68971587, 56.59620573, 67.45836303,
       70.21901294, 66.8654579 , 74.74135841, 77.8740242 , 73.01943753,
       76.24064436, 78.64746096, 69.86312251, 62.28039767, 71.32468455,
       68.8935325 , 82.03965016, 79.1402864 , 81.83548596, 81.81191974,
       81.74595079, 50.6681441 , 67.18500333, 69.56018236, 70.95238469,
       73.24836213, 75.2797839 , 76.50174826, 65.42336919, 71.13450585,
       68.45067773, 73.05730279, 74.91790468, 71.91389403, 51.24774968,
       77.70399587, 77.40939231, 71.89636119, 74.77090451, 71.21250208,
       58.46855769, 78.61238992, 56.93710496, 65.76597944, 71.6700761 ,
       63.97374664, 63.20358287, 79.30212418, 68.52756575, 78.58244619,
       76.36600073, 61.79133963, 68.59910821, 73.13136283, 60.51708708,
       68.66799809, 78.88389873, 74.8544376 , 76.30337951, 69.21634761,
       51.83795904, 72.00456244, 76.89547896, 78.2127234 , 76.30309445,
       53.46071035, 69.68719311, 74.91717251, 84.12803945, 80.74250259,
       73.53646525, 64.72628586, 75.02752728, 75.04469563, 84.72336529,
       54.58675435, 74.58940734, 73.44950179, 81.63254553, 69.66454168,
       61.57631663, 81.31814278, 75.23477975, 69.91070454, 41.91781158,
       79.14762977, 72.38787207, 75.0371796 , 70.01147345, 75.34794783,
       63.43536915, 71.07195285, 72.02726625, 59.79552832, 74.72831534,
       50.6243856 , 77.55642544, 75.26185701, 75.68956214, 73.07600367,
       62.72712273, 77.85925158, 60.43036793, 76.35254908, 77.86539438,
       70.16778195, 60.7499624 , 80.81070046, 63.55660398, 76.11642596,
       69.23003875, 76.89008763, 74.56459211, 63.96495627, 68.39911039,
       59.95020875, 74.99632828, 65.0539372 , 73.59988859, 77.72820549,
       43.63776907, 56.65612649, 72.13249384, 70.42007165, 60.02090801,
       67.8805543 , 80.02960548, 73.82507246, 68.14723633, 61.76894567,
       67.27708371, 75.63531656, 71.41640801, 74.80634213, 73.60954346,
       49.92757518, 70.8978413 , 64.84927998, 69.98202513, 62.2971257 ,
       80.30108363, 70.6564779 , 56.03351202, 53.44816904, 50.05021496,
       73.90231979, 54.67519933, 70.42744528, 76.11413279, 67.16286739,
       69.95093249, 73.61784831, 59.42646154, 61.08243266, 72.54806071,
       58.04318205, 83.0874773 , 74.92855553, 78.5786869 , 65.941708  ,
       59.40741802, 68.47575921, 74.50984558, 61.94748947, 79.22305748,
       63.93775986, 67.65694836, 60.38812848, 76.78435499, 71.3625639 ,
       66.54372063, 63.04910289, 66.35823183, 64.09599158, 70.14257513,
       69.11476453, 76.69104411, 71.36328758, 62.26949141, 57.01464529,
       75.56826498, 82.2390792 , 76.06815229, 52.75640142, 75.83977502,
       76.36033306, 71.15400773, 63.15642255, 71.14557665, 61.20497924,
       58.5203859 , 70.91598834, 62.44857574, 72.30222596, 61.31723368,
       69.70743551, 78.13568635, 75.60802244, 68.67555236, 68.50775878,
       78.5072526 , 73.2562093 , 73.48008539, 70.34956178, 70.48727895,
       64.79588117, 69.41840342, 70.53215906, 76.08721159, 70.47427355,
       69.69753089, 72.00942271, 57.98190087, 74.11614677, 70.88404652,
       72.82476591, 68.08319366, 64.11598741])

In [28]:
y_test

array([82.        , 79.2       , 78.4       , 81.1       , 88.        ,
       66.8       , 50.        , 75.4       , 74.7       , 74.3       ,
       55.        , 55.5       , 75.5       , 73.8       , 51.6       ,
       86.        , 65.4       , 73.4       , 68.5       , 74.1       ,
       71.5       , 73.7       , 62.8       , 58.1       , 58.6       ,
       67.8       , 77.7       , 72.4       , 77.3       , 79.9       ,
       71.6       , 59.9       , 55.        , 55.3       , 78.6       ,
       81.3       , 72.4       , 66.4       , 79.6       , 81.3       ,
       77.6       , 74.1       , 62.2       , 82.7       , 57.2       ,
       73.5       , 81.        , 59.4       , 69.        , 63.3       ,
       67.7       , 67.7       , 74.6       , 61.8       , 56.4       ,
       82.        , 89.        , 73.2       , 81.8       , 65.4       ,
       77.6       , 73.        , 69.        , 57.5       , 74.1       ,
       71.1       , 72.7       , 73.        , 59.7       , 73.        ,
       54.9       , 52.        , 74.8       , 81.        , 78.        ,
       76.2       , 69.4       , 79.3       , 56.8       , 78.1       ,
       74.6       , 63.6       , 76.3       , 69.1       , 73.9       ,
       66.8       , 73.        , 82.2       , 71.1       , 71.9       ,
       79.8       , 67.9       , 80.        , 73.9       , 81.7       ,
       44.5       , 74.4       , 73.9       , 58.2       , 78.        ,
       75.7       , 73.3       , 74.6       , 89.        , 74.8       ,
       81.3       , 77.3       , 69.8       , 72.2       , 57.        ,
       53.8       , 75.        , 73.7       , 62.2       , 77.5       ,
       74.8       , 57.9       , 68.5       , 51.5       , 78.        ,
       57.1       , 57.6       , 72.        , 72.1       , 65.7       ,
       61.2       , 56.2       , 81.8       , 56.4       , 59.6       ,
       66.2       , 77.4       , 73.9       , 81.2       , 45.6       ,
       78.1       , 78.7       , 71.2       , 74.8       , 79.7       ,
       63.        , 58.2       , 68.3       , 77.5       , 53.8       ,
       83.        , 75.5       , 73.8       , 75.6       , 49.7       ,
       71.        , 78.2       , 54.9       , 66.5       , 73.9       ,
       54.        , 56.        , 64.8       , 73.2       , 69.        ,
       78.3       , 55.        , 72.6       , 61.8       , 68.9       ,
       48.2       , 56.7       , 71.7       , 75.7       , 77.4       ,
       74.7       , 46.8       , 79.6       , 63.8       , 76.3       ,
       78.9       , 61.8       , 47.1       , 75.1       , 71.6       ,
       64.5       , 78.2       , 73.        , 73.6       , 68.5       ,
       70.        , 74.8       , 45.3       , 64.3       , 68.8       ,
       75.        , 48.5       , 72.2       , 74.5       , 74.1       ,
       74.9       , 73.        , 64.7       , 67.8       , 71.7       ,
       54.4       , 83.        , 58.        , 74.6       , 75.2       ,
       73.9       , 78.5       , 52.        , 76.1       , 86.        ,
       74.1       , 89.        , 51.3       , 79.9       , 53.8       ,
       57.6       , 81.2       , 55.3       , 69.7       , 51.2       ,
       79.7       , 83.        , 78.1       , 68.1       , 73.9       ,
       62.8       , 56.5       , 69.22493169, 63.8       , 63.2       ,
       63.        , 74.2       , 73.1       , 79.2       , 78.3       ,
       71.9       , 72.9       , 72.6       , 75.4       , 65.        ,
       75.5       , 75.5       , 48.2       , 85.        , 76.        ,
       72.        , 72.6       , 82.        , 57.        , 53.5       ,
       45.4       , 76.8       , 63.8       , 88.        , 59.2       ,
       73.9       , 51.4       , 81.3       , 80.        , 68.8       ,
       46.6       , 82.        , 79.7       , 85.        , 81.5       ,
       81.5       , 81.8       , 78.5       , 77.2       , 77.5       ,
       78.8       , 68.4       , 63.        , 65.2       , 54.        ,
       67.        , 75.        , 65.        , 57.3       , 75.4       ,
       84.        , 63.1       , 72.9       , 75.        , 51.4       ,
       58.5       , 59.1       , 73.1       , 63.7       , 59.7       ,
       41.        , 70.        , 80.        , 72.7       , 47.7       ,
       55.7       , 69.3       , 74.5       , 73.3       , 69.        ,
       68.1       , 86.        , 66.9       , 71.        , 49.6       ,
       76.        , 81.1       , 65.6       , 74.6       , 63.6       ,
       73.3       , 72.8       , 75.2       , 71.3       , 69.4       ,
       76.7       , 74.1       , 67.4       , 72.4       , 49.2       ,
       65.4       , 74.7       , 73.8       , 75.4       , 68.7       ,
       47.8       , 67.7       , 62.        , 66.        , 87.        ,
       46.6       , 67.7       , 76.9       , 54.3       , 66.        ,
       61.5       , 49.6       , 55.4       , 78.7       , 67.9       ,
       73.4       , 58.4       , 62.3       , 73.3       , 75.2       ,
       67.        , 76.2       , 57.6       , 74.8       , 68.        ,
       74.9       , 81.        , 78.1       , 74.1       , 76.8       ,
       73.        , 74.1       , 77.5       , 60.        , 72.3       ,
       65.        , 81.        , 72.6       , 81.5       , 55.        ,
       74.8       , 62.7       , 45.3       , 81.3       , 67.7       ,
       52.6       , 49.2       , 57.4       , 48.5       , 63.8       ,
       72.2       , 73.8       , 78.7       , 83.        , 72.9       ,
       78.        , 71.2       , 68.1       , 63.7       , 75.1       ,
       73.8       , 81.1       , 81.1       , 78.        , 81.6       ,
       78.4       , 52.1       , 64.9       , 66.7       , 69.22493169,
       73.7       , 73.2       , 74.7       , 70.        , 69.4       ,
       74.        , 68.9       , 77.2       , 73.6       , 62.5       ,
       79.7       , 73.5       , 74.5       , 74.1       , 73.7       ,
       56.5       , 82.5       , 56.        , 65.8       , 67.3       ,
       58.3       , 62.4       , 82.2       , 75.        , 79.7       ,
       76.2       , 62.5       , 66.5       , 76.5       , 55.7       ,
       73.4       , 79.7       , 76.6       , 87.        , 77.        ,
       51.4       , 71.4       , 78.        , 78.5       , 74.5       ,
       52.4       , 66.        , 74.9       , 84.        , 79.8       ,
       74.5       , 58.7       , 73.9       , 74.5       , 84.        ,
       49.        , 77.7       , 73.6       , 79.9       , 72.3       ,
       62.1       , 77.3       , 73.1       , 68.7       , 46.        ,
       82.1       , 68.4       , 74.7       , 75.4       , 76.6       ,
       64.6       , 68.4       , 73.5       , 59.2       , 74.7       ,
       51.        , 74.9       , 77.5       , 77.3       , 75.3       ,
       62.6       , 72.2       , 53.2       , 74.8       , 83.5       ,
       69.3       , 51.7       , 89.        , 69.1       , 73.5       ,
       71.5       , 75.        , 73.        , 57.9       , 66.        ,
       59.3       , 72.2       , 62.5       , 73.3       , 74.2       ,
       49.8       , 48.2       , 67.5       , 71.5       , 63.3       ,
       66.8       , 87.        , 74.8       , 69.6       , 69.1       ,
       74.7       , 72.4       , 73.        , 79.1       , 77.        ,
       52.7       , 72.        , 65.7       , 71.        , 59.4       ,
       74.8       , 76.3       , 57.3       , 52.9       , 52.7       ,
       78.        , 52.1       , 72.        , 79.6       , 71.4       ,
       75.9       , 72.4       , 59.        , 59.6       , 74.6       ,
       54.6       , 79.9       , 74.8       , 79.4       , 68.        ,
       58.9       , 67.2       , 72.2       , 66.7       , 84.        ,
       63.1       , 65.1       , 58.8       , 76.3       , 69.7       ,
       64.2       , 63.3       , 72.6       , 63.        , 72.7       ,
       71.8       , 76.6       , 79.        , 58.7       , 64.2       ,
       72.3       , 88.        , 78.1       , 36.3       , 75.4       ,
       76.3       , 62.8       , 61.7       , 65.        , 59.7       ,
       45.7       , 67.9       , 51.9       , 78.5       , 66.5       ,
       77.6       , 85.        , 77.8       , 74.4       , 66.1       ,
       76.6       , 72.6       , 69.5       , 65.1       , 66.7       ,
       59.4       , 67.        , 66.6       , 77.5       , 73.        ,
       74.        , 74.1       , 56.1       , 71.        , 77.        ,
       76.1       , 71.8       , 72.        ])

In [35]:
from sklearn.metrics import mean_squared_error

In [37]:
mean_squared_error(y_test, y_pred)

17.785257613712012